"""tours

Revision ID: 29f6be5f6362
Revises: 181c73212a3e
Create Date: 2025-08-31 15:31:49.859020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f6be5f6362'
down_revision = '181c73212a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS tour_images CASCADE")
    op.execute("DROP TABLE IF EXISTS image CASCADE")
    op.execute("DROP TABLE IF EXISTS booking CASCADE")
    op.execute("DROP TABLE IF EXISTS review CASCADE")
    op.execute("DROP TABLE IF EXISTS tour_schedule CASCADE")
    op.execute("DROP TABLE IF EXISTS tour_categories CASCADE")
    op.execute("DROP TABLE IF EXISTS tour CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###fla